name: Test and Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        run: node index.js

      - name: Push changes if tests pass
        if: success()
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
          git add .
          git commit -m "Auto-push: Tests passed"
          git push origin main

        env:
          PAT: ${{secrets.PAT }}